# Dependencies
markdown: kramdown
highlighter: rouge

plugins:
    - jekyll-sitemap

# File rules
exclude: [vendor, Dangerfile, Gemfile, Gemfile.lock, LICENSE, README.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, new_draft.sh, github_issue_generator.rb]

# Permalinks
permalink: /:title/

# Site
title: 'Swift Weekly Brief'
description: 'A community-driven weekly newsletter about Swift.org'
logo: /img/logo.png

repo_name: cn

twitter:
    username: swiftlybrief

# Setup
excerpt_separator: <!--excerpt-->

# Data
links:
    rss: '/cn/feed.xml'
    twitter: 'https://twitter.com/swiftlybrief'
    github: 'https://github.com/SwiftWeekly/cn'
    issue: 'https://github.com/SwiftWeekly/cn/issues/new'
    pull: 'https://github.com/SwiftWeekly/cn/compare'
    applenews: 'https://apple.news/TIlGIYluMTGWA-CIToVtF4Q'
